# Generated by Django 5.1.1 on 2024-11-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='deal_price',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_listed',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='price',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='product',
        ),
    ]
