# Generated by Django 5.1.1 on 2024-10-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order',
        ),
    ]
