# Generated by Django 5.1.1 on 2024-10-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_cancelorder_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CancelOrder',
        ),
    ]
