# Generated by Django 5.1.1 on 2024-10-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_order_cancellation_reason_delete_cancelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ReturnItem',
        ),
    ]
