# Generated by Django 5.1.1 on 2024-11-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0009_checkout_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='return_status',
            field=models.CharField(blank=True, default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
