# Generated by Django 5.1.1 on 2024-11-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_app', '0001_initial'),
        ('order_app', '0013_orderitems_discount_price_orderitems_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='address_field',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address_app.address'),
        ),
    ]
