# Generated by Django 5.1.1 on 2024-11-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='user',
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='order',
            field=models.ForeignKey(default=103, on_delete=django.db.models.deletion.CASCADE, related_name='orderAddress', to='order_app.order'),
            preserve_default=False,
        ),
    ]
