# Generated by Django 5.1.1 on 2024-11-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0016_remove_orderaddress_user_orderaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.OneToOneField(default=103, on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='order_app.order'),
            preserve_default=False,
        ),
    ]
