# Generated by Django 5.1.1 on 2024-10-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_cart_item_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
