# Generated by Django 5.1.1 on 2024-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_alter_wallettransation_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransation',
            name='transaction_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('cancellation', 'Cancellation'), ('debited', 'Debited'), ('referral', 'Referral')], max_length=20),
        ),
    ]
